### ISSUE TITLE
Quotes are not properly escaped on iOS

### ISSUE THREAD

**Issue by larslockefeer** [PicnicSupermarket/localicious#33]
## Steps to reproduce
Given the following Localicipe:
```
IOS:
  Module:
    Screen:
      Element:
        COPY:
          en: "This is a <a href=\"https://github.com/PicnicSupermarket/localicious\">link</a>"
```
## Observed behaviour
Localicious generates the following Localizable.strings file:
```
"Module.Screen.Element.COPY" = "This is a <a href="https://github.com/PicnicSupermarket/localicious">link</a>";
```

This leads to the following error in Xcode: `Localizable.strings:1:1: read failed: Couldn't parse property list because the input data was in an invalid format`

## Expected behaviour
Running `plutil` leads us to the culprit:

```
2020-05-28 13:51:12.415 plutil[35933:1269394] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 1. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
Localizable.strings: Unexpected character " at line 1
```

From this, we can conclude that the following Localizable.strings file is expected by Xcode:

```
"Module.Screen.Element.COPY" = "This is a <a href=\"https://github.com/PicnicSupermarket/localicious\">link</a>";
```
