### ISSUE TITLE
Duplicate keys in the Localicipe should result in an error

### ISSUE THREAD

**Issue by LcTwisk** [PicnicSupermarket/localicious#42]
Currently, if you by mistake define duplicate keys in the Localicipe, the previous entries will always be overwritten by the last key in the file.

**The problem**:
Let's say there's a Localicipe that looks like:

```
COLLECTION-A:
  Onboarding:
    Login:
      InputField: 
        Placeholder: 
          COPY:
            en: "Username"
      InputField: 
        Placeholder: 
          COPY:
            en: "E-mail"
```

The key `Onboarding.Login.InputField.Placeholder` is defined twice, as a result, the second entry will be overwritten by the first one. This behaviour might be confusing, entries that accidentally have duplicated keys will get lost. 

**Proposal**
Improve the validation by throwing a proper error that indicates that duplicated entries are not allowed in the Localicipe.
