### ISSUE TITLE
Generate additional function without args for quantity strings

### ISSUE THREAD

**Issue by jhildensperger** [PicnicSupermarket/localicious#46]
Let's take an example of formatting a string for a number of things. The yml could look like this:
```yml
ThingCount:
    COPY:
        ZERO:
            en: 'no things'
        ONE:
            en: '%1{{d}} thing'
        OTHER:
            en: '%1{{d}} things
```

That would generate a function like this:
```swift
public static func ThingCount(quantity: Int, args: CVarArg...) -> LocaliciousData {
    ...
}
```

And you would use it like this:
```swift
let numberOfThings: Int = 10
L.Base.ThingCount(quantity: numberOfThings, args: numberOfThings)
```

My assumption is that the most common use case for strings with number formats would be a single `arg` so it is a little weird to pass the same `arg` twice. A nice solution could be to also generate a function that calls the current function with the `quantity` param as the args like this:

```swift
public static func ThingCount(quantity: Int) -> LocaliciousData {
    return ThingCount(quantity: quantity, args: quantity) 
}
```

Then you get a nice clean looking usage for the simple, single arg case.

```swift
let numberOfThings: Int = 10
L.Base.ThingCount(quantity: numberOfThings)
```
