### ISSUE TITLE
Keys starting with digits do not compile for iOS 

### ISSUE THREAD

**Issue by jhildensperger** [PicnicSupermarket/localicious#52]
This should be caught by validation 

For example, this:

```yaml
SHARED:
    Widget:
      1CoolTitle:
        COPY:
          en: "😎 title"
          nl: "😎 titel"
```

Renders the following which does not compile:

```swift
public struct L {
    public struct Widget {
        public static let 1CoolTitle = LocaliciousData(
            accessibilityIdentifier: "Widget.1CoolTitle",
            accessibilityHintKey: nil,
            accessibilityLabelKey: nil,
            accessibilityValueKey: nil,
            translationKey: "Widget.1CoolTitle.COPY",
            translationArgs: []
        )
    }
```
